version: "3.7"
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "10000:10000"

  service-http:
    image: mendhak/http-https-echo:23
    hostname: service-http
#    volumes:
#    - /etc/example/certs/front-proxy-crt.pem:/app/fullchain.pem
#    - /etc/example/certs/front-proxy-key.pem:/app/privkey.pem
    environment:
    - HTTPS_PORT=0
    - HTTP_PORT=80
